version: '3.8'

services:
  app:
    build: .
    depends_on:
      - mysql
    container_name: nest_168
    ports:
      - "3000:3000"
    environment:
      PORT: 3306 
      DB_USERNAME: root
      DB_PASSWORD: 12345
      DB_HOST: localhost
      DB_NAME: data_store
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: kelis
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
  node_modules:
